// gemini.js
import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from "dotenv";

dotenv.config();

const API_KEY = process.env.NEXT_PUBLIC_GEMINI_API_KEY;

if (!API_KEY) {
  throw new Error(
    "Missing NEXT_PUBLIC_GEMINI_API_KEY in .env. Get one from https://aistudio.google.com/app/apikey"
  );
}

const genAI = new GoogleGenerativeAI(API_KEY);
const modelName = "gemini-2.5-flash";

export async function askFromGemini(prompt) {
  console.log({ prompt });

  try {
    const model = genAI.getGenerativeModel({ model: modelName });

    const result = await model.generateContent(prompt.trim());
    console.log({ result });

    // ✅ CORRECT EXTRACTION BASED ON YOUR ACTUAL RESPONSE SHAPE
    const text =
      result?.response?.candidates?.[0]?.content?.parts?.[0]?.text || "";

    if (!text) {
      console.error("❌ Empty Gemini response:", result);
      return "No response generated by AI.";
    }

    return text;
  } catch (err) {
    console.error("❌ Gemini API Error:", err);
    return `Gemini API Error: ${err.message || err}`;
  }
}

// Example usage:
// (async () => {
//   const prompt = "Explain the theory of relativity in simple terms.";
//   const response = await askFromGemini(prompt);
//   console.log("AI Response:", response);
// })();
